### ISSUE TITLE
Post Shapekey Mesh in Blender 2.80 does not work properly

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#2482]
<img width="335" alt="Screen Shot 2019-07-12 at 12 24 40" src="https://user-images.githubusercontent.com/3952687/61104307-1d037800-a4a0-11e9-89ba-9dce64fdd6e7.png">
<img width="317" alt="Screen Shot 2019-07-12 at 12 24 46" src="https://user-images.githubusercontent.com/3952687/61104309-1d9c0e80-a4a0-11e9-9beb-57908287d64d.png">

In Blender 2.79 if I "Objects In" Mesh data with shapekeys animation, it will respect the shapekeys in post.

In Blender 2.80 pre-release, the mesh data with shapekeys does not transfer in SV properly.

**Comment by enzyme69** [comment]
This is how it looks with Blender 2.80 Sverchok:
<img width="283" alt="Screen Shot 2019-07-12 at 12 26 20" src="https://user-images.githubusercontent.com/3952687/61104348-46240880-a4a0-11e9-88e5-9889d3180e22.png">

**Comment by zeffii** [comment]
yep, the API for `objects in`  _post_ modifiers wasn't completely the same when i implemented the 2.80 version.   Is it OK when the input mesh doesn't have modifiers?

The api for `object.to_mesh()` wasn't feature complete in 2.80 last time i looked.

**Comment by enzyme69** [comment]
still not OK even with or without modifier. Shapekeys have no effect.
-- 


------------------------------------------------------------
- Jimmy Gunawan
http://blendersushi.blogspot.com.au
http://mayaspiral.blogspot.com.au
http://houdoodles.blogspot.com.au
http://puppetar.blogspot.com.au

**Comment by zeffii** [comment]
so, the "post" part in your question is irrelevant.

**Comment by zeffii** [comment]
@enzyme69  ask your Blender dev friends if  `object.to_mesh()` can take shapekeys into account **or** how does one get the result of shapekeys into a temporary mesh for inspection.

**Comment by enzyme69** [comment]
<img width="813" alt="Screen Shot 2019-08-15 at 9 56 03 pm" src="https://user-images.githubusercontent.com/3952687/63093174-7e3ecf80-bfa7-11e9-9f63-a269c85d34f5.png">

Yeah maybe Jacques Lucke or Omar can kind of explain, but with Animation Nodes, it does read the post resulting mesh of Shapekeys or Alembic...

SV 2.80 does not do this yet...

**Comment by zeffii** [comment]
you need to make a simple blend, with minimal description that I/anyone can load (with whatever object included in the scene, or the zip if it need to be imported) .

so all i have to do is follow instructions/load .blend (whatever), then i (or whoever is interested) can try stuff. i'm a little busy (but we might have to add a global "get depsgraph" in the post_frame change event (or other event) and make a globally accessible ' evaluated depsgraph ' property.

it's all super dirty stuff ... until someone makes a good demo file.

**Comment by enzyme69** [comment]
Hi @zeffii thanks for quick reply.

Yes, basically I was wondering why post Alembic Modifier and Shapekeys are no longer working in B280 of Sverchok.

Below is an example using 279 and 280 setup and Alembic animation:
[abc_instancing.zip](https://github.com/nortikin/sverchok/files/3505549/abc_instancing.zip)

Shapekeys is the same, not working in 280

**Comment by enzyme69** [comment]
https://developer.blender.org/T69028

Animation Nodes Mesh Info output is actually respecting shapekeys... weird...

**Comment by zeffii** [comment]
because this isn't an essential part of Sverchok (at least... not to me) the shapekeys / post modifiers effects on the mesh are not implemented yet.  it's not "weird". There is a pullrequest which touches on a topic that also relies on getting the current "dependency_graph" (for particles...) that might allow us to enable the `post` feature again. no promises.

i should probably warn you that the new depsgraph changes a few things for us, for good and for bad. the negative result for us might be particularly `noticable` if you have obj_in and particles and a `bmeshviewer` in one `nodetree`.

If each frame we obtain a dependencygraph "state" , for for-instance the `obj in` node, this graph is valid until the chain-of-data reaches "obj out" (like BMeshViewer),  in my mind it is not yet defined/clear how the nodetree would behave if after the BMeshViewer has written mesh data you want to pick up that data again using obj_in or something...or particles..or even dupligroups...

we'll see..
