### ISSUE TITLE
"Duplicate Objects along Edge" node turns red when setting the scaling to "none"

### ISSUE THREAD

**Issue by morph3us-net** [nortikin/sverchok#2484]
## Problem statement
"Duplicate Objects along Edge" node turns red when setting the scaling to "none".

## Steps to reproduce
I am still trying to make train tracks and currently trying out the "Duplicate Objects along Edge" node. Everything works fine, except that the duplicated meshes get malformed. 

You can see the original grey box in the middle and the distorted clones in blue around it. I tried to change the scaling mode to off, however this just errors out the node.
https://ibb.co/pwt4768

## Expected result
Exact copies of the source mesh distributed along the curve. (They should rotate around their z axis, according to the curve, however.)

## Sverchok version
0.6.0.0, the "b28_prelease_master" fork

**Comment by portnov** [comment]
There should be an error in blender's text buffer named "sverchok.log" (or in blender's console output). Please attach it here.

**Comment by vicdoval** [comment]
Fixed 😄 , 
Thanks again for reporting. It was due the new matrix multiplication method.
Please update and try again

**Comment by morph3us-net** [comment]
Yes, it works now! Thank you very much for your effort!
As a log was requested earlier and I still get some errors, I thought I might add it here:
You can download my blend file from my mega drive here: 
https://mega.nz/#!ghRnDKBa!O-dDmwqhBU6gqqvkw0jY0HuH6yxqQStvneplRrL0KQw

> sv: import settings
sv: import all modules
[Errno 2] No such file or directory: 'C:\\Users\\morph3us\\AppData\\Roaming\\Blender Foundation\\Blender\\2.80\\datafiles\\sverchok\\sv_fx.wad'
seeing this message means you need to generate an uptoken
sv: append app.handlers:
sv: enable internal debug logging.
INFO:sverchok.utils.logging:162:log level, 20
>  ______ _    _ _______  ______ _______ _     _  _____  _     _
> /______  \  /  |______ |_____/ |       |_____| |     | |____/
> ______/   \/   |______ |    \_ |_____  |     | |_____| |    \_
> initialized.
> 
> sv: version: 0.6.0.0
sv: 300 nodes.
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'label'
Read blend: C:\Users\morph3us\.Nimi Places\Containers\Quick access\Projects\GoogleMaps\SverchokTest001.blend
INFO:root:140:Initializing Sverchok logging. Blender version 2.80 (sub 74), Sverchok version 0.6.0.0
ERROR:sverchok.core.update_system:162:Node Path Length had exception: No data passed into socket `Vertices'
Traceback (most recent call last):
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\core\update_system.py", line 325, in do_update_general
    node.process()
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\nodes\analyzer\path_length.py", line 117, in process
    meshes = self.get_data()
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\nodes\analyzer\path_length.py", line 96, in get_data
    vertices = si['Vertices'].sv_get()
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\sockets.py", line 356, in sv_get
    source_data = SvGetSocket(self, deepcopy = True if self.needs_data_conversion() else deepcopy)
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\core\socket_data.py", line 108, in SvGetSocket
    raise SvNoDataError(socket)
sverchok.core.socket_data.SvNoDataError: No data passed into socket `Vertices'
Warning: class SvGroupNodeMonad_2200721793222 contains a property which should be an annotation!
C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\utils\__init__.py:10
    assign as a type annotation: SvGroupNodeMonad_2200721793222.stop_
update event: link count changed 14829.015
ERROR:sverchok.core.update_system:162:Node VD Experimental had exception: No data passed into socket `edges'
Traceback (most recent call last):
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\core\update_system.py", line 325, in do_update_general
    node.process()
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\nodes\viz\vd_draw_experimental.py", line 548, in process
    data = self.get_data()
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\nodes\viz\vd_draw_experimental.py", line 474, in get_data
    prope = edges_socket.sv_get(deepcopy=False, default=[[]])
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\sockets.py", line 478, in sv_get
    return self.convert_data(SvGetSocket(self, deepcopy), implicit_conversions)
  File "C:\Blender\blender-2.80rc1-windows64\2.80\scripts\addons_contrib\sverchok\core\socket_data.py", line 108, in SvGetSocket
    raise SvNoDataError(socket)
> 

Also, as a future Idea (I really dont want to sound greedy, please forgive me): I would like to "duplicate objects along edge" based on meter. (as in: one box every 2 meters, I am sure this is achievable now, too, but would be awesome to have right in the node. Right now, I get a lot of boxes in between my sampled points. Illustration: https://ibb.co/Qbh3Z4v )

**Comment by vicdoval** [comment]
Check this example from the path length node docs:
Using the Path Length node to place circles of one meter of diameter along a given curve.  ![](https://user-images.githubusercontent.com/10011941/51251931-c4449e00-199a-11e9-9e75-69ead34fad64.png)
If you add the "duplicate objects along edges" after the UVconnection node i think  you can achieve what you are trying

**Comment by zeffii** [comment]
@portnov i also don't know how to use that node
https://blender.stackexchange.com/questions/164178/sverchok-duplicating-an-object-along-a-path/164364#164364

**Comment by zeffii** [comment]
reminder to self, the N panel has an "scale all axis" to prevent deformation :) 

![image](https://user-images.githubusercontent.com/619340/72734704-8fb18680-3b9a-11ea-8a4b-0ec485f1c4b4.png)
