### ISSUE TITLE
Sverchok stops updating after save/reload Blender 3.0 Alpha

### ISSUE THREAD

**Issue by sna-scourtney** [nortikin/sverchok#4246]
## Problem statement

I have been using Sverchok about two weeks (and loving it), and I fully realize Blender 3.0 Alpha is not supported officially by the Blender team or by Sverchok's developer. I am posting this issue only to give information about a problem, as an early alert to the Sverchok community.

Sverchok appears to work very well under Blender 3.0 Alpha; I was able to install the plugin and create Sverchok geometry with no problems at all. I have not tested every node, but the basics work.

The problem is that after saving the Blender file and re-opening it, the Sverchok graph is present and the geometry is drawn in the 3D viewport, but making changes to the Sverchok nodes does not change the viewport geometry. As far as I can tell, there are no errors reported in the console, so I think there may be a Blender API callback that is no longer active, or it may be passing parameters to the callback function that Sverchok is treating as an empty call.

## Steps to reproduce

1. Create an empty project in Blender 3.0 Alpha, with Sverchok installed as usual.
2. Create one or more Sverchok node graphs that draw geometry in the viewport.
3. Save the Blender file and exit Blender.
4. Reload Blender and open the project file. Verify that "live update" is started in Sverchok.
5. Make some changes to the Sverchok node graph.

## Expected result

The 3D viewport should reflect the changes made to the Sverchok node graph.

## Actual result

There are no apparent error messages, but the 3D viewport does not change. Stopping and restarting live update does not change the situation, nor does clicking the button to rebuild the node tree. 

I was able to reproduce this problem with a freshly-created empty project in Blender 3.0 Alpha, and repeating the same steps in Blender 2.93 does **not** have this problem; the Sverchok geometry saves and reloads perfectly. I have the same plugins installed for both Blender versions.

## Sverchok version

Updated Master branch as of 2021-07-20.

**Comment by Durman** [comment]
It looks close to this bug #4229. Are you sure you use the last version of Sverchok because that bug was fixed recently. I tried reproduce it on the latest Sverchok and Blender 3.0 versions and without success.

**Comment by sna-scourtney** [comment]
> It looks close to this bug #4229. Are you sure you use the last version of Sverchok because that bug was fixed recently. I tried reproduce it on the latest Sverchok and Blender 3.0 versions and without success.

I _thought_ I was on a version newer than 11 days, but I'll update to the very latest as of today and see if I can still reproduce the problem.

**Comment by sna-scourtney** [comment]
Confirmed, this is fixed in the current version as of 2021-07-28. I had updated before, but I wonder if I happened to do so just slightly before this bug was fixed. Regardless, it is working correctly now, so I concur that this ticket can be closed. Thanks for the info.
