### ISSUE TITLE
is SV Line vectorized? - if so how does it work

### ISSUE THREAD

**Issue by enzyme69** [nortikin/sverchok#793]
I just found out something that will crash Sverchok.

Apart that SV Line is still not vectorized, unlike the Circle, I realized that if I plug in Integer Range 0 - 10 with step 1, I think that zero killed Sverchok, when I plug the Int Range into Line :(

**Comment by ly29** [comment]
I cannot reproduce the problem.
please provide the file and if not at least a legible screen shot of the layout.

**Comment by ly29** [comment]
That said line node is very old and contains some strange code.

**Comment by zeffii** [comment]
didn't someone make an alternate line node with _orientation_ so we didn't have to transform the output 
https://github.com/nortikin/sverchok/issues/421  (oh..that was me)

also..:
https://github.com/nortikin/sverchok/issues/690

**Comment by zeffii** [comment]
tho.. I would probably make the orientation an vector input now (also vectorized)..

**Comment by ly29** [comment]
But also making a line node with range and float in it is trivial. Especially with polar coordinates. 

The "problem" with line is that it is kind vectorized but in different way where step can be a list with different steps. Which is kind of unexpected.

**Comment by zeffii** [comment]
maybe have `self.vectorize` bool to act as flow control, and cause two different kinds of paths..

**Comment by enzyme69** [comment]
I make a video screen recording to show the issue:
[https://youtu.be/FGdjC_l5-bg](url)

**Comment by ly29** [comment]
Good, I will try to reproduce the crash today.

**Comment by ly29** [comment]
Okay I can reproduce the crash by setting ```start``` in ```List Range Int``` to 0.
The crash seems to be related to the OpenGL getting bad polygon input data.
![skarmavbild 2016-08-15 kl 09 27 56](https://cloud.githubusercontent.com/assets/6241382/17658267/cd980868-62ca-11e6-9c13-95bfb03d3395.png)
So this is two, issues, one for Line, this one. 
Will create new one for the crash.

**Comment by ly29** [comment]
Now the crashing should be fixed, @enzyme69 please test.

**Comment by enzyme69** [comment]
I updated and still crashes Blender.

When plugging Integer Range node (with zero value range) into the Line.

**Comment by enzyme69** [comment]
I restarted Blender, and retried the setup, with MK2 and Viewer Draw as
output. And.... seems to be working find and no longer crashing now.

I can close this. But LINE is still not doing vectorize.

**Comment by enzyme69** [comment]
![screen shot 2016-08-16 at 12 40 55](https://cloud.githubusercontent.com/assets/3952687/17686303/c0abeac2-63ae-11e6-8779-16e4f4e72fda.png)

Can't have line with different vertex number per matrix?

**Comment by nortikin** [comment]
Plug range to range and you will get that result!

**Comment by nortikin** [comment]
Vectorization in two levels.

**Comment by enzyme69** [comment]
Nortikin is correct, it works with multiple range to range node. Thanks! All good now! 👯
